services:
  api:
    build: .
    image: auricaichatregistry.azurecr.io/cryptoanalysisproject:latest
    ports:
      - "8000:8000"  # FastAPI
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data: